# Generated by Django 3.0.8 on 2020-07-28 10:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appname', '0003_auto_20200728_1936'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='c_wirter',
            new_name='c_writer',
        ),
    ]
