# Generated by Django 3.0.8 on 2020-08-11 08:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appname', '0006_post_likes'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='title',
            new_name='location',
        ),
    ]
